### ISSUE TITLE
Dockerize Flask API Microservice

### ISSUE THREAD

**Issue by Bluette1** [Bluette1/postbee-tracker-api#10]
## Description:
Set up Docker and Docker Compose configurations for the Flask API microservice to ensure consistent development and deployment environments.

### Acceptance Criteria:
- Development and production Docker configurations
- Docker Compose setup for local development
- Integration with other PostBee microservices
- Documentation for Docker usage

### Technical Tasks:

1. Base Dockerfile Setup
- Create Dockerfile with Python base image
- Set up virtual environment
- Install system dependencies
- Copy application code
- Configure entry point
```python
# Dockerfile
FROM python:3.11-slim

# Set working directory
WORKDIR /app

# Set environment variables
ENV PYTHONDONTWRITEBYTECODE 1
ENV PYTHONUNBUFFERED 1
ENV FLASK_ENV=production

# Install system dependencies
RUN apt-get update && apt-get install -y \
    gcc \
    && rm -rf /var/lib/apt/lists/*

# Install Python dependencies
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

# Copy application code
COPY . .

# Run gunicorn
CMD ["gunicorn", "--bind", "0.0.0.0:5000", "wsgi:app"]
```

2. Development Environment
```yaml
# docker-compose.dev.yml
version: '3.8'

services:
  flask_api:
    build: 
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "5000:5000"
    volumes:
      - .:/app
    environment:
      - FLASK_ENV=development
      - FLASK_APP=app.py
      - FLASK_DEBUG=1
      - MONGODB_URI=mongodb://mongodb:27017/postbee
    depends_on:
      - mongodb
      - redis

  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

volumes:
  mongodb_data:
  redis_data:
```

3. Production Environment
```yaml
# docker-compose.prod.yml
version: '3.8'

services:
  flask_api:
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    environment:
      - FLASK_ENV=production
      - MONGODB_URI=mongodb://mongodb:27017/postbee
      - REDIS_URL=redis://redis:6379/0
    depends_on:
      - mongodb
      - redis
    deploy:
      replicas: 3
      restart_policy:
        condition: on-failure
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  mongodb:
    image: mongo:latest
    volumes:
      - mongodb_data:/data/db
    command: ["mongod", "--auth"]
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_ROOT_PASSWORD}

  redis:
    image: redis:alpine
    volumes:
      - redis_data:/data
    command: redis-server --requirepass ${REDIS_PASSWORD}

volumes:
  mongodb_data:
  redis_data:
```

4. Development Dockerfile
```dockerfile
# Dockerfile.dev
FROM python:3.11-slim

WORKDIR /app

ENV PYTHONDONTWRITEBYTECODE 1
ENV PYTHONUNBUFFERED 1
ENV FLASK_ENV=development

RUN apt-get update && apt-get install -y \
    gcc \
    && rm -rf /var/lib/apt/lists/*

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

# Additional development dependencies
RUN pip install --no-cache-dir \
    pytest \
    pytest-cov \
    black \
    flake8 \
    debugpy

COPY . .

CMD ["flask", "run", "--host=0.0.0.0", "--port=5000"]
```

5. Create .dockerignore
```
# .dockerignore
__pycache__
*.pyc
*.pyo
*.pyd
.Python
env/
venv/
.env
.git
.gitignore
.pytest_cache
.coverage
htmlcov/
dist/
build/
*.egg-info/
.DS_Store
```

#### Additional Tasks:
- Set up environment variables management
- Configure logging for containers
- Set up health checks
- Implement container monitoring
- Create Docker networking configuration
- Set up volume management
- Configure CI/CD pipeline integration

#### Technical Considerations:
- Use multi-stage builds for production
- Implement proper caching strategies
- Security best practices:
  * Non-root user
  * Minimal base images
  * Security scanning
- Container orchestration readiness
- Backup strategies
- Performance optimization

#### Documentation Tasks:
1. Create README with:
  - Setup instructions
  - Development workflow
  - Production deployment
  - Environment variables
  - Troubleshooting guide

2. Document:
  - Build process
  - Container management
  - Scaling strategies
  - Backup and restore procedures
  - Security considerations

Priority: High
